In [2]:
# include dependencies for df manipulation and visualization
%matplotlib inline
from matplotlib import style
style.use('fivethirtyeight')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import datetime as dt

# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy import create_engine, MetaData, Table, Column, Numeric,insert, Integer, VARCHAR, update, text, delete, func, inspect
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
from sqlalchemy import Column, Integer, String, Float
from sklearn.feature_extraction.text import TfidfVectorizer as tf_idf

# import Flask
from flask import Flask

# import Scipy
import scipy.stats as st

# Input data in the "../Resources/" directory.
import seaborn as sns
import os
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [16, 10]
plt.rcParams['font.size'] = 14
width = 0.75
from wordcloud import WordCloud, STOPWORDS
import gensim.models
from gensim.models import Word2Vec
import multiprocessing
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')
from collections import defaultdict
import string
from sklearn.preprocessing import StandardScaler
sns.set_palette(sns.color_palette('tab20', 20))
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
from datetime import date, timedelta
import operator 
import re
#stops = stopwords.words("english")
from tqdm import  tqdm
from collections import Counter
import warnings
warnings.filterwarnings('ignore')
# print(os.listdir(""))
from IPython.display import IFrame
from IPython.core.display import display, HTML
from flask import Flask, jsonify


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
rds_connection_string = "postgresql://songlyrics:gatechfinalproject@lyrical-analysis.cxe3nmyieexj.us-east-1.rds.amazonaws.com:5432/musicalDbanalytics"
engine = create_engine(rds_connection_string)

In [5]:
# get columns from the albumbestsellers table
inspector = inspect(engine)
inspector.get_columns("albumbestsellers")

[{'autoincrement': False,
  'comment': None,
  'default': None,
  'name': 'artist',
  'nullable': True,
  'type': TEXT()},
 {'autoincrement': False,
  'comment': None,
  'default': None,
  'name': 'album',
  'nullable': True,
  'type': TEXT()},
 {'autoincrement': False,
  'comment': None,
  'default': None,
  'name': 'released',
  'nullable': True,
  'type': INTEGER()},
 {'autoincrement': False,
  'comment': None,
  'default': None,
  'name': 'genre',
  'nullable': True,
  'type': TEXT()},
 {'autoincrement': False,
  'comment': None,
  'default': None,
  'name': 'total_certified_copies_from_available_markets',
  'nullable': True,
  'type': TEXT()},
 {'autoincrement': False,
  'comment': None,
  'default': None,
  'name': 'claimed_sales_millions',
  'nullable': True,
  'type': INTEGER()}]

In [6]:
# get columns from the station table
inspector.get_columns("masterlyrics")

[{'autoincrement': False,
  'comment': None,
  'default': None,
  'name': 'artist',
  'nullable': True,
  'type': TEXT()},
 {'autoincrement': False,
  'comment': None,
  'default': None,
  'name': 'song',
  'nullable': True,
  'type': TEXT()},
 {'autoincrement': False,
  'comment': None,
  'default': None,
  'name': 'lyrics',
  'nullable': True,
  'type': TEXT()}]

In [7]:
# pull records from masterlyrics
sql = text('SELECT * from masterlyrics')
  
# Fetch all the records
result = engine.execute(sql).fetchall()
print(result)

[('Carly Rae Jepsen', 'Cup Of Tea', "A cup of tea, a cup of tea I've been driving all night, you won't turn on your light that easily A neon sign offers some shelter across the street Gu ... (998 characters truncated) ... ding your waist like she'd give you a taste so easily I won't cry, no, I'll just watch, and I will see And I'll say my last goodbye with a cup of tea"), ('Carly Rae Jepsen', 'Everywhere You Look (The Fuller House Theme)', '"Whatever happened to predictability? The milkman, the paperboy, the evening TV? How did I get delivered here? Somebody tell me please Cause this old ... (5 characters truncated) ... d is just really confusing me Clouds as mean as you\'ve ever seen Ain\'t a bird that knows your tune Then a little voice inside of you whispers ""Kid'), ('XXXTENTACION', 'The Explanation', "17 My collection of nightmares, thoughts, and real life situations I've lived 17 is the number tattooed on the right side of my head My own personal  ... (342 characters truncated) .

In [8]:
# pull records from album music box
sql_music_box = text("""SELECT albumbestsellers.artist,
albumbestsellers.album,
albumbestsellers.claimed_sales_millions,
masterlyrics.lyrics,
masterlyrics.song FROM albumbestsellers
INNER JOIN albumjoiner
ON albumjoiner.album2 = albumbestsellers.album
INNER JOIN masterlyrics
ON masterlyrics.song = albumjoiner.song
WHERE albumbestsellers.album = 'Music Box'""")
  
# Fetch all the records
result_music_box = engine.execute(sql_music_box).fetchall()
print(result_music_box)



[('Mariah Carey', 'Music Box', 28, "When I am lost You shine a light for me and set me free When I am low You wash away my tears And take me through The loneliness And emptiness Through ... (765 characters truncated) ... urrounding me And baby, all I have, I want to give to thee Want to give you all of my love Now and forever my love All I have, I want to give to thee", 'Music Box'), ('Mariah Carey', 'Music Box', 28, "Do you know How it feels Lying here without you, baby? You could never understand what's happening to me So alone Nothing's real I just dream about y ... (706 characters truncated) ... by And even though you're not my friend (Oh, no, no, no) I would give my all To have you here Just to hold you once again Just to hold you once again", 'Just To Hold You Once Again'), ('Mariah Carey', 'Music Box', 28, "If you only knew What I feel for you If you only lived for me The way I live for you I'd be in heaven My dreams would come true 'Cause all I've ever  ... (512 characters trun

In [9]:
# pull records from masterlyrics
sql_a = text('SELECT * from albumbestsellers')
  
# Fetch all the records
result_album = engine.execute(sql_a).fetchall()
print(result_album)

[('Michael Jackson', 'Thriller', 1982, 'Pop, post-disco, funk, rock', '50.2 US: 34 million[9] JPN: 100,000[10] UK: 4.5 million[11] GER: 1.5 million[12] FRA: 1 million[13] CAN: 2 million[14] AUS: 1.12 million[15] MEX: 2.6 ... (82 characters truncated) ... WI: 300,000[21] AUT: 400,000[22] FIN: 119,061[23] NZ: 180,000[24][25] HKG: 15,000[26] DEN: 480,000[27] DEN: 60,000[28] HUN: 6,000[29] POR: 40,000[30]', 70), ('AC/DC', 'Back in Black', 1980, 'Hard rock', '29.5 US: 25 million[9] UK: 600,000[11] GER: 1 million[12] FRA: 600,000[13] CAN: 1 million[14] AUS: 840,000[15] ITA: 150,000[18] ARG: 180,000[31] SWI: 100,000[21] AUT: 50,000[22]', 50), ('Whitney Houston / various artists', 'The Bodyguard', 1992, 'R&B, soul, pop, soundtrack', '32.4 US: 18 million[9] JPN: 3 million[33] UK: 2.25 million[11] GER: 1.75 million[12] FRA: 1.72 million[13] CAN: 1.4 million[14] AUS: 350,000[15] BRA: ... (3 characters truncated) ... 2 million[34] NLD: 400,000[17] SWE: 350,000[19] SPA: 800,000[35] ARG: 350,000[31]

In [10]:
# convert to dataframes
lyrics_df = pd.DataFrame(result)
lyrics_df.rename(columns={0: "artist", 1: "song", 2: "lyric"}, inplace=True)
lyrics_df.head()
lyrics_df.shape

artist                                          song  \
0  Carly Rae Jepsen                                    Cup Of Tea   
1  Carly Rae Jepsen  Everywhere You Look (The Fuller House Theme)   
2      XXXTENTACION                               The Explanation   
3       Wiz Khalifa                                      The Last   
4       Wiz Khalifa                              This Time Around   

                                               lyric  
0  A cup of tea, a cup of tea I've been driving a...  
1  "Whatever happened to predictability? The milk...  
2  17 My collection of nightmares, thoughts, and ...  
3  Y'll already know what it is We the last... At...  
4  "Just the wind in my hair from the top 'cause ...

(5801, 3)

In [11]:

print(lyrics_df["lyric"])
lyrics_df["lyric"] = lyrics_df["lyric"].str.replace(r":]</i>", "")
lyrics_df["lyric"] = lyrics_df["lyric"].str.replace(r"<i>", "")
lyrics_df["lyric"] = lyrics_df["lyric"].str.replace(r"</i>", "")

specialChars = '''.,?!#$%^&*()"@[;]'''

for specialChar in specialChars:
  lyrics_df["lyric"] = lyrics_df["lyric"].str.replace(specialChar, '')



print(lyrics_df["lyric"])
lyrics_df.to_csv("word.csv")

0       A cup of tea, a cup of tea I've been driving a...
1       "Whatever happened to predictability? The milk...
2       17 My collection of nightmares, thoughts, and ...
3       Y'll already know what it is We the last... At...
4       "Just the wind in my hair from the top 'cause ...
                              ...                        
5796    <i>[Patrick Stump:]</i> Do you, do-do you reme...
5797    "Saturday, Saturday, Saturday, Saturday, Satur...
5798    Woah... (New York City sing that out) Woah... ...
5799    Ooh The fire is burning The room's all aglow O...
5800    Ooh, yeah Lord I pray That in my lifetime ther...
Name: lyric, Length: 5801, dtype: object
0       A cup of tea a cup of tea I've been driving al...
1       Whatever happened to predictability The milkma...
2       17 My collection of nightmares thoughts and re...
3       Y'll already know what it is We the last At ni...
4       Just the wind in my hair from the top 'cause I...
                              .

In [12]:
lyrics_df["lyric"] = lyrics_df["lyric"].str.lower()
lyrics_df.head()

artist                                          song  \
0  Carly Rae Jepsen                                    Cup Of Tea   
1  Carly Rae Jepsen  Everywhere You Look (The Fuller House Theme)   
2      XXXTENTACION                               The Explanation   
3       Wiz Khalifa                                      The Last   
4       Wiz Khalifa                              This Time Around   

                                               lyric  
0  a cup of tea a cup of tea i've been driving al...  
1  whatever happened to predictability the milkma...  
2  17 my collection of nightmares thoughts and re...  
3  y'll already know what it is we the last at ni...  
4  just the wind in my hair from the top 'cause i...

In [13]:
lyrics_df["lyric"] = lyrics_df["lyric"].str.replace('\d+', '')
lyrics_df["lyric"]

0       a cup of tea a cup of tea i've been driving al...
1       whatever happened to predictability the milkma...
2        my collection of nightmares thoughts and real...
3       y'll already know what it is we the last at ni...
4       just the wind in my hair from the top 'cause i...
                              ...                        
5796    patrick stump do you do-do you remember when w...
5797    saturday saturday saturday saturday saturday s...
5798    woah new york city sing that out woah i promis...
5799    ooh the fire is burning the room's all aglow o...
5800    ooh yeah lord i pray that in my lifetime there...
Name: lyric, Length: 5801, dtype: object

In [14]:
lyricsList = lyrics_df["lyric"].str.split(' ')

In [15]:
# assess stop words included in StopWords
print(stop)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [16]:
# Create a list of n empty sub lists

filtered_lyric = [[] for i in range(len(lyricsList))]


# remove stop words and append to list of lists
for row in range(len(lyricsList)):
  for word in lyricsList[row]:
    if word not in stop:
      filtered_lyric[row].append(word)

# print(lyricsList[0])
# print(filtered_lyric[0])

In [17]:
# create dataframe for lyric words excluded from stop word library
filtered_lyric_df = pd.DataFrame(filtered_lyric)
filtered_lyric_df['processedLyric'] = filtered_lyric_df[filtered_lyric_df.columns[1:]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1
)
filtered_lyric_df['processedLyric'] = filtered_lyric_df['processedLyric'].str.replace(",", " ")
filtered_lyric_df.head()

0           1               2         3         4        5  \
0       cup         tea             cup       tea      i've  driving   
1  whatever    happened  predictability   milkman  paperboy  evening   
2            collection      nightmares  thoughts      real     life   
3      y'll     already            know      last     night   that's   
4      wind        hair             top    'cause       got  booking   

            6      7          8           9  ...   865   866   867   868  \
0       night   turn      light      easily  ...  None  None  None  None   
1          tv    get  delivered    somebody  ...  None  None  None  None   
2  situations   i've      lived              ...  None  None  None  None   
3      lights  shine        ask  stewardess  ...  None  None  None  None   
4     flights    i'm       town       heart  ...  None  None  None  None   

    869   870   871   872   873  \
0  None  None  None  None  None   
1  None  None  None  None  None   
2  None  None  None  None  None   
3  None  None  None  None  None   
4  None  None  None  None  None   

                                      processedLyric  
0  tea cup tea i've driving night turn light easi...  
1  happened predictability milkman paperboy eveni...  
2  collection nightmares thoughts real life situa...  
3  already know last night that's lights shine as...  
4  hair top 'cause got booking flights i'm town h...  

[5 rows x 875 columns]

In [18]:
# concat dataframes to create consolidated dataframe, reseting index to create a formal index column for future merging

lyrics_processed_df = pd.concat([lyrics_df, filtered_lyric_df["processedLyric"]], axis = 1)
lyrics_processed_df = lyrics_processed_df.rename_axis('indexColumn').reset_index()
lyrics_processed_df

indexColumn            artist  \
0               0  Carly Rae Jepsen   
1               1  Carly Rae Jepsen   
2               2      XXXTENTACION   
3               3       Wiz Khalifa   
4               4       Wiz Khalifa   
...           ...               ...   
5796         5796      Fall Out Boy   
5797         5797      Fall Out Boy   
5798         5798      Shawn Mendes   
5799         5799      Mariah Carey   
5800         5800      Mariah Carey   

                                                  song  \
0                                           Cup Of Tea   
1         Everywhere You Look (The Fuller House Theme)   
2                                      The Explanation   
3                                             The Last   
4                                     This Time Around   
...                                                ...   
5796                           Favorite Record (Remix)   
5797             Saturday Night's Alright For Fighting   
5798  Never Be Alone & Hey There Delilah (Live Medley)   
5799                 Miss You Most (At Christmas Time)   
5800                                            I Pray   

                                                  lyric  \
0     a cup of tea a cup of tea i've been driving al...   
1     whatever happened to predictability the milkma...   
2      my collection of nightmares thoughts and real...   
3     y'll already know what it is we the last at ni...   
4     just the wind in my hair from the top 'cause i...   
...                                                 ...   
5796  patrick stump do you do-do you remember when w...   
5797  saturday saturday saturday saturday saturday s...   
5798  woah new york city sing that out woah i promis...   
5799  ooh the fire is burning the room's all aglow o...   
5800  ooh yeah lord i pray that in my lifetime there...   

                                         processedLyric  
0     tea cup tea i've driving night turn light easi...  
1     happened predictability milkman paperboy eveni...  
2     collection nightmares thoughts real life situa...  
3     already know last night that's lights shine as...  
4     hair top 'cause got booking flights i'm town h...  
...                                                 ...  
5796  stump do-do remember drove drove drove night d...  
5797  saturday saturday saturday saturday saturday s...  
5798  new york city sing woah promise one day i'll a...  
5799  fire burning room's aglow outside december win...  
5800  yeah lord pray lifetime come day world wake un...  

[5801 rows x 5 columns]

In [21]:
# allow split of lyric with def get_w2vdf

def get_w2vdf(df):
    w2v_df = pd.DataFrame(lyrics_processed_df["processedLyric"]).values.tolist()
    for i in range(len(w2v_df)):
        w2v_df[i] = w2v_df[i][0].split(" ")
    return w2v_df

In [22]:
# train model for word2vec 

def train_w2v(w2v_df):
    cores = multiprocessing.cpu_count()
    w2v_model = Word2Vec(min_count=4,
                         window=4,
                         size=300, 
                         alpha=0.03, 
                         min_alpha=0.0007, 
                         sg = 1,
                         workers=cores-1)
    
    w2v_model.build_vocab(w2v_df, progress_per=10000)
    w2v_model.train(w2v_df, total_examples=w2v_model.corpus_count, epochs=100, report_delay=1)
    return w2v_model

In [23]:
# run lyrics through model to generate array

w2v_df = get_w2vdf(lyrics_processed_df)
w2v_model = train_w2v(w2v_df)


In [24]:
# test array generation
w2v_model["apple"]

array([ 2.86229074e-01,  1.16004050e+00,  2.53601640e-01,  8.91410589e-01,
        8.26162159e-01, -4.28227901e-01, -1.20328918e-01,  2.02799872e-01,
       -2.78409719e-01, -1.00982261e+00, -5.96100152e-01,  7.15750098e-01,
       -3.29053432e-01, -1.86134860e-01, -1.10732615e-01, -8.26900482e-01,
        2.02798754e-01, -2.45137677e-01,  9.17607427e-01,  4.04335678e-01,
        3.83153260e-01,  1.79508805e-01, -5.61159313e-01,  5.15886068e-01,
        7.58226752e-01, -2.74947643e-01,  5.03956638e-02,  3.75744164e-01,
        1.25960991e-01,  5.85742176e-01, -5.79841673e-01, -2.02475768e-02,
       -5.90059161e-01,  8.49643946e-01, -2.07751200e-01,  1.08481216e+00,
       -2.41848335e-01, -1.20114096e-01, -4.17408466e-01, -6.34289086e-01,
       -4.84924972e-01,  9.76326704e-01, -1.35413897e+00, -6.57455504e-01,
       -6.09545112e-01,  5.00847518e-01, -1.12116277e-01, -3.69419396e-01,
        7.75373220e-01, -9.81612131e-02, -3.28176975e-01, -7.98722982e-01,
       -3.04115534e-01,  

In [25]:
model_output_test = w2v_model.wv.most_similar(positive=["eminem"])
model_output_test

[('gary', 0.3567866086959839),
 ('chka-chka', 0.35085970163345337),
 ('stan', 0.3164904713630676),
 ('ahem', 0.31288230419158936),
 ('gwen', 0.3127955496311188),
 ('mathers', 0.31213057041168213),
 ('hitchcock', 0.30974480509757996),
 ('tourniquet', 0.30906856060028076),
 ('taps', 0.3085756301879883),
 ('pre-hook', 0.3084377944469452)]

In [26]:

mariah_df = lyrics_processed_df[lyrics_processed_df["artist"] == "Mariah Carey"]
mariahIndexList = mariah_df["indexColumn"].tolist()

eminem_df = lyrics_processed_df[lyrics_processed_df["artist"] == "Eminem"]
eminemIndexList = eminem_df["indexColumn"].tolist()

print("Eminem: ", eminemIndexList)
print("Mariah: ", mariahIndexList)

# for artist in artistList:
#   if "artist" == "Mariah Carey":
#     mariahList.append(lyrics_processed_df["indexColumn"])
#   elif lyrics_processed_df["artist"] == "Emimen":
#     eminemList.append(lyrics_processed_df["indexColumn"])

# wordList = pd.DataFrame(columns = ["TopWord", "TopTen"])

# def wordListPop(listNameInput, listNameOutput):
#   for word in listNameInput:
#     w2v_model.wv.most_similar(positive=[word])
#     print(word)
#     print(w2v_model.wv.most_similar(positive=[word]))



Eminem:  [1302, 1492, 1796, 1797, 1828, 2068, 2075, 2076, 2090, 2091, 2785, 2803, 2925, 3642, 3646, 3654, 3655, 3656, 3657, 3666, 3667, 3670, 3675, 3676, 3677, 3695, 3696, 3697, 3720, 3721, 3727, 3742, 3743, 3765, 3766, 3767, 3768, 3769, 3776, 3777, 3778, 3779, 3795, 3796, 3803, 3838, 3839, 3840, 3841, 3860, 3861, 3862, 3866, 3879, 3880, 3881, 3882, 3887, 3900, 3925, 3932, 3933, 3961, 3962, 3972, 4010, 4063, 4079, 4080, 4085, 4088, 4089, 4090, 4092, 4093, 4094, 4106, 4121, 4122, 4142, 4148, 4149, 4150, 4151, 4153, 4163, 4164, 4172, 4180, 4181, 4182, 4183, 4186, 4188, 4189, 4190, 4191, 4205, 4216, 4224, 4240, 4241, 4251, 4259, 4260, 4261, 4262, 4263, 4264, 4364, 4365, 4380, 4381, 4382, 4383, 4389, 4401, 4413, 4414, 4432, 4433, 4446, 4447, 4448, 4449, 4465, 4466, 4471, 4472, 4473, 4474, 4485, 4486, 4505, 4562, 4569, 4570, 4583, 4584, 4591, 4592, 4593, 4594, 4595, 4601, 4602, 4616, 4617, 4619, 4626, 4627, 4628, 4629, 4630, 4635, 4636, 4667, 4668, 4669, 4673, 4675, 4689, 4701, 4702, 4716, 

In [27]:
# from sklearn.feature_extraction.text import Tf1dfVectorizer
vectorizerTFIDF = tf_idf()
T = vectorizerTFIDF.fit_transform(lyrics_processed_df["processedLyric"])
# print(X.get_feature_names())

In [28]:
# test top 10 words based on TFIDF for each lyric
df = pd.DataFrame(T[2025].T.todense(), index = vectorizerTFIDF.get_feature_names(), columns=["TF-IDF"])
df = df.sort_values("TF-IDF", ascending = False)
df.head(10)

TF-IDF
livin        0.659947
lovin        0.427705
ain          0.324337
baby         0.278570
fall         0.147776
proposition  0.115449
ah           0.113389
ambition     0.107959
heartaches   0.106562
conquer      0.105286

In [71]:
# traverse through the top 10 (based on TFIDF) for Mariah lyrics

mariahWordBank = pd.DataFrame()

for mariahIndex in mariahIndexList:
  df1 = pd.DataFrame(T[mariahIndex].T.todense(), index = vectorizerTFIDF.get_feature_names(), columns=["TF-IDF"])

  df1 = df1.sort_values("TF-IDF", ascending = False)
  df1 = df1.head(10)
  df1 = df1.assign(albumIndex = mariahIndex)
  df1 = df1.reset_index()
  df1 = df1.rename(columns = {"index": "key_word"})
  mariahWordBank = pd.concat([mariahWordBank,df1])

print(f"Shape: {mariahWordBank.shape}\n")
print(f"Head of Mariah:\n {mariahWordBank.head()}\n")
print(f"Tail of Mariah:\n {mariahWordBank.tail()}")

# push to a csv
mariahWordBank.to_csv('MariahWordBankTop10.csv', encoding='utf-8', index=False)

Shape: (2780, 3)

Head of Mariah:
    key_word    TF-IDF  albumIndex
0    divine  0.663524        1158
1     night  0.481157        1158
2    yonder  0.150818        1158
3  rejoices  0.150818        1158
4  glorious  0.141034        1158

Tail of Mariah:
   key_word    TF-IDF  albumIndex
5    bring  0.195945        5800
6      day  0.184106        5800
7     come  0.157232        5800
8       us  0.153592        5800
9   please  0.147317        5800


In [72]:
# generate list of Mariah top 10 words
mariahWordList = mariahWordBank["key_word"].tolist()

In [73]:
# traverse through top 10 words for Mariah at song level and identify each word's nearest 10 words

mariah10 = pd.DataFrame()

for mariahWord in mariahWordList:
  try:
    df1 = pd.DataFrame(w2v_model.wv.most_similar(positive=[mariahWord]))
    df1 = df1.assign(key_word = mariahWord)
    df1 = df1.rename(columns = {0: "closestWord", 1: "word2vec"})
    mariah10 = pd.concat([mariah10,df1])
  
  except KeyError:
    pass

print(f"Shape: {mariah10.shape}\n")
print(f"Head of Mariah10:\n {mariah10.head()}\n")
print(f"Tail of Mariah10:\n {mariah10.tail()}")
mariah10.to_csv('MariahNearest.csv', encoding='utf-8', index=False)

Shape: (25140, 3)

Head of Mariah10:
     closestWord  word2vec key_word
0      savior's  0.431543   divine
1       angels'  0.414538   divine
2        reigns  0.399005   divine
3  intervention  0.364904   divine
4      proclaim  0.364039   divine

Tail of Mariah10:
   closestWord  word2vec key_word
5     you-u-u  0.321855   please
6  se-se-sexy  0.319891   please
7        gogo  0.311528   please
8  situation:  0.309414   please
9   chka-chka  0.303350   please


In [74]:
# traverse through the top 10 (based on TFIDF) for Eminem lyrics

eminemWordBank = pd.DataFrame()

for eminemIndex in eminemIndexList:
  df1 = pd.DataFrame(T[eminemIndex].T.todense(), index = vectorizerTFIDF.get_feature_names(), columns=["TF-IDF"])

  df1 = df1.sort_values("TF-IDF", ascending = False)
  df1 = df1.head(10)
  df1 = df1.assign(albumIndex = eminemIndex)
  df1 = df1.reset_index()
  df1 = df1.rename(columns = {"index": "key_word"})
  eminemWordBank = pd.concat([eminemWordBank,df1])

print(f"Shape: {eminemWordBank.shape}\n")
print(f"Head of Eminem:\n {eminemWordBank.head()}\n")
print(f"Tail of Eminem:\n {eminemWordBank.tail()}")
eminemWordBank.to_csv('EminemWordBankTop10.csv', encoding='utf-8', index=False)

Shape: (3770, 3)

Head of Eminem:
   key_word    TF-IDF  albumIndex
0      pee  0.663151        1302
1      ass  0.242762        1302
2     jams  0.221316        1302
3    nelly  0.190417        1302
4     move  0.187291        1302

Tail of Eminem:
        key_word    TF-IDF  albumIndex
5          mean  0.068949        5784
6         cause  0.037278        5784
7          know  0.030271        5784
8    presidente  0.000000        5784
9  presidential  0.000000        5784


In [75]:
eminemWordList = eminemWordBank["key_word"].tolist()

In [76]:
# traverse through top 10 words for Eminem at song level and identify each word's nearest 10 words

eminem10 = pd.DataFrame()

for eminemWord in eminemWordList:
  try:
    df1 = pd.DataFrame(w2v_model.wv.most_similar(positive=[eminemWord]))
    df1 = df1.assign(key_word = eminemWord)
    df1 = df1.rename(columns = {0: "closestWord", 1: "word2vec"})
    eminem10 = pd.concat([eminem10,df1])
  
  except KeyError:
    pass

print(f"Shape: {eminem10.shape}\n")
print(f"Head of Eminem10:\n {eminem10.head()}\n")
print(f"Tail of Eminem10:\n {eminem10.tail()}")
eminem10.to_csv('EminemNearest.csv', encoding='utf-8', index=False)


Shape: (28370, 3)

Head of Eminem10:
   closestWord  word2vec key_word
0       flask  0.328768      pee
1     rihanna  0.313413      pee
2   alleviate  0.305708      pee
3     g-wagon  0.288858      pee
4       kriss  0.284756      pee

Tail of Eminem10:
   closestWord  word2vec      key_word
5       bonus  0.311567  presidential
6      ronald  0.311493  presidential
7         e-z  0.307767  presidential
8    yo-ho-ho  0.302074  presidential
9       roams  0.300981  presidential


In [70]:

eminem10["key_word"].value_counts().sort_values

<bound method Series.sort_values of shit          270
eminem        250
like          220
shady         210
cause         190
             ... 
developing     10
biters         10
today          10
lord           10
hoes           10
Name: key_word, Length: 1605, dtype: int64>

In [ ]:
df = pd.DataFrame.from_dict(mariahWordBankDict) 
df
print(df)

5800
0       [pray]
1       [lord]
2   [lifetime]
3  [unclouded]
4      [dream]
5      [bring]
6        [day]
7       [come]
8         [us]
9     [please]

          5800
0       [pray]
1       [lord]
2   [lifetime]
3  [unclouded]
4      [dream]
5      [bring]
6        [day]
7       [come]
8         [us]
9     [please]


In [ ]:
# !pip install texthero
import texthero as hero
lyrics_processed_df['tfidf'] = hero.tfidf(lyrics_processed_df["processedLyric"])

NameError: ignored

In [ ]:
lyrics_processed_df['tfidf']

0       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
1       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
2       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
3       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
4       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
                              ...                        
5796    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
5797    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
5798    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
5799    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
5800    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
Name: tfidf, Length: 5801, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer


# To create a Count Vectorizer, we simply need to instantiate one.
# There are special parameters we can set here when making the vectorizer, but
# for the most basic example, it is not needed.
vectorizerCount = CountVectorizer()

C = vectorizerCount.fit(lyrics_processed_df["lyric"])
# print(C.shape)
print(C)

CountVectorizer()


In [ ]:
# Now, we can inspect how our vectorizer vectorized the text
# This will print out a list of words used, and their index in the vectors
print('Vocabulary: ')
print(vectorizerCount.vocabulary_)
print(vectorizerTFIDF.vocabulary_)

Vocabulary: 
{'cup': 5634, 'of': 16356, 'tea': 23933, 've': 25746, 'been': 1904, 'driving': 7095, 'all': 543, 'night': 15982, 'you': 27234, 'won': 26840, 'turn': 25115, 'on': 16470, 'your': 27256, 'light': 13584, 'that': 24146, 'easily': 7335, 'neon': 15863, 'sign': 21525, 'offers': 16368, 'some': 22218, 'shelter': 21236, 'across': 165, 'the': 24153, 'street': 23059, 'guess': 10273, 'll': 13726, 'drink': 7075, 'my': 15634, 'trouble': 24978, 'down': 6946, 'with': 26782, 're': 19147, 'over': 16781, 'me': 14583, 'howl': 11335, 'at': 1202, 'room': 20146, 'like': 13608, 'wolf': 26829, 'to': 24505, 'moon': 15289, 'going': 9910, 'crazy': 5372, 'ring': 19933, 'one': 16475, 'more': 15319, 'time': 24420, 'it': 12214, 'bring': 2938, 'footsteps': 9022, 'sit': 21649, 'and': 740, 'wait': 26154, 'but': 3252, 'getting': 9681, 'cold': 4628, 'in': 11762, 'here': 10884, 'hours': 11311, 'dear': 5970, 'are': 1001, 'someone': 22222, 'else': 7537, 'tonight': 24570, 'distance': 6687, 'was': 26279, 'killing': 

In [ ]:
# If we would like to actually create a vector, we can do so by passing the
# text into the vectorizer to get back counts
vectorCount = vectorizerCount.transform(lyrics_processed_df["processedLyric"])
vectorTFIDF = vectorizerTFIDF.transform(lyrics_processed_df["processedLyric"])
print(vectorCount)
print(vectorizerTFIDF)

  (0, 165)	1
  (0, 1428)	1
  (0, 2938)	1
  (0, 3387)	1
  (0, 4628)	2
  (0, 5372)	1
  (0, 5555)	1
  (0, 5634)	7
  (0, 5869)	1
  (0, 5970)	2
  (0, 6687)	2
  (0, 7075)	1
  (0, 7095)	1
  (0, 7335)	2
  (0, 7537)	2
  (0, 8588)	2
  (0, 8638)	1
  (0, 9022)	1
  (0, 9681)	2
  (0, 9765)	1
  (0, 9910)	1
  (0, 9936)	1
  (0, 10273)	2
  (0, 11107)	1
  (0, 11240)	2
  :	:
  (5800, 15809)	2
  (5800, 16387)	3
  (5800, 16475)	2
  (5800, 16479)	1
  (5800, 16568)	1
  (5800, 17874)	3
  (5800, 18237)	8
  (5800, 18242)	1
  (5800, 19147)	1
  (5800, 20415)	1
  (5800, 20904)	1
  (5800, 21236)	1
  (5800, 21417)	1
  (5800, 24176)	3
  (5800, 24420)	1
  (5800, 25307)	2
  (5800, 25607)	4
  (5800, 26170)	2
  (5800, 26334)	2
  (5800, 26344)	1
  (5800, 26346)	1
  (5800, 26359)	1
  (5800, 26755)	1
  (5800, 26910)	3
  (5800, 27124)	1
TfidfVectorizer()


In [ ]:




# Our final vector:
print('Full vector: ')
print(vectorCount.toarray())

# Or if we wanted to get the vector for one word:
print('Hot vector: ')
print(vectorizerCount.transform(['apple']).toarray())

# Or if we wanted to get multiple vectors at once to build matrices
print('Hot and one: ')
# print(vectorizerCount.transform(['apple', 'tea']).toarray())

# We could also do the whole thing at once with the fit_transform method:
# print('One swoop:')
# new_text = ['Today is the day that I do the thing today, today']
# new_vectorizer = CountVectorizer()
# print(new_vectorizer.fit_transform(new_text).toarray())

Full vector: 
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Hot vector: 
[[0 0 0 ... 0 0 0]]
Hot and one: 
